In [1]:
import pandas as pd
import os

# Access metadata from repository
pd.read_csv('https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3A3baf7289-bf90-4db3-ad11-58785c09b26e')

# Load data
prey = pd.read_csv('https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3A23d42528-1048-45d4-85d1-7e13b666e744')

In [2]:
type(prey)

pandas.DataFrame

In [4]:
pd.set_option("display.max_columns", None)

In [6]:
### Preliminary exploration
# First 5 rows
prey.head(5)

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institutionCode,coordinateUncertaintyInMeters,basisOfRecord,individualCount,datasetKey,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,2020,iNaturalist,684.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,1,141.925064,199.384964,89.602631,727.380493,151.920853,1.809903,89.132339,391.141083,7.979710,13.979711,391.141083,139.787125,53.000000,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,2021,iNaturalist,6.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,2,136.366943,165.841537,104.141464,609.651916,126.271736,1.001933,87.368050,318.303192,8.236301,12.390024,318.301269,83.996452,53.266750,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,2021,iNaturalist,31.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,3,82.885788,161.338638,19.747343,724.200195,120.836441,4.910511,70.099121,353.376068,49.060783,77.778824,342.061676,144.624817,47.098640,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,2016,iNaturalist,15.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,4,171.959030,221.238907,130.363754,323.523682,62.686253,1.000000,87.075172,179.273834,4.989321,9.743295,163.154465,118.763413,53.612831,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,2019,iNaturalist,16.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,5,171.996231,214.353073,136.138779,273.203491,58.141060,1.000000,91.661606,162.390411,4.000000,7.109778,142.560562,91.184349,50.718666,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104

In [10]:
#Last 5 rows idk how
prey.tail(5)

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institutionCode,coordinateUncertaintyInMeters,basisOfRecord,individualCount,datasetKey,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
111151,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,33.660853,-115.721380,1980-04-10T00:00:00Z,10.0,4.0,1980,MCZ,3036.0,PRESERVED_SPECIMEN,1.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111152,200.539291,297.044373,111.539291,131.447403,21.313471,0.464611,50.358723,45.637127,7.404018,33.626942,44.287857,158.105041,43.560184,7319.267090,393.674744,34.807846,358.866913,217.827911,227.579758,0.925702,548.778870,barren,1187.127441
111152,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,35.933333,-116.716667,1998-03-26T00:00:00Z,26.0,3.0,1998,MCZ,NaN,PRESERVED_SPECIMEN,2.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111153,230.166946,344.166931,117.216942,49.012608,8.380343,1.000000,50.700531,21.778294,4.391233,9.430344,19.810688,163.872391,39.000000,8878.634766,442.558167,26.608175,415.950012,141.977646,273.793304,7.429875,-13.553053,grassland,792.632141
111153,Insecta,Hymenoptera,Formicidae,Liometopum,Liometopum occidentale,34.156833,-118.726833,2010-05-21T00:00:00Z,21.0,5.0,2010,MCZ,NaN,PRESERVED_SPECIMEN,40.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111154,161.271088,216.747421,116.372208,499.779816,106.116470,0.000000,96.797958,289.033630,4.470360,11.920360,279.654663,128.898209,53.252625,3962.391846,291.092560,51.291302,239.801269,118.917351,209.822205,2.387915,347.122986,grassland,4219.497559
111154,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,32.989167,-116.658500,2010-05-25T00:00:00Z,25.0,5.0,2010,MCZ,NaN,PRESERVED_SPECIMEN,30.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111155,140.342300,217.269943,76.576256,559.577881,102.406273,3.000000,78.449997,293.045471,25.936378,36.503853,270.567810,154.063629,49.683960,5537.141602,315.901031,8.395161,307.505859,83.576256,199.928528,6.917791,981.674377,grassland,4865.626465
111155,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,36.251400,-117.731400,1992-09-02T00:00:00Z,2.0,9.0,1992,NTNU-VM,100000.0,PRESERVED_SPECIMEN,1.0,1bec5de3-758c-4ed2-ab13-1597601ad07a,111156,102.202797,197.274719,18.412592,294.105835,48.132629,6.007638,59.663151,133.747376,27.179491,31.660290,133.747376,141.080276,41.000000,7069.728027,293.179962,-47.896355,341.076324,20.241280,171.378082,23.553705,1913.307861,grassland,1628.940918

In [ ]:
#Show column names, number of non-null values, and dtype for each column
prey.info()

In [8]:
#Shows the number of unique
prey.dtypes

class                                str
order                                str
family                               str
genus                                str
species                              str
lat                              float64
long                             float64
eventDate                            str
day                              float64
month                            float64
year                               int64
institutionCode                      str
coordinateUncertaintyInMeters    float64
basisOfRecord                        str
individualCount                  float64
datasetKey                           str
ID                                 int64
bio1                             float64
bio10                            float64
bio11                            float64
bio12                            float64
bio13                            float64
bio14                            float64
bio15                            float64
bio16                            float64
bio17                            float64
bio18                            float64
bio19                            float64
bio2                             float64
bio3                             float64
bio4                             float64
bio5                             float64
bio6                             float64
bio7                             float64
bio8                             float64
bio9                             float64
dist                             float64
dem90_hf                         float64
lc_class                             str
ndvi                             float64
dtype: object

In [ ]:
#Shows uhh
prey.shape

In [ ]:
#Lists the names of columns in a dataframe
prey.columns

In [9]:
prey.nunique()
#prey.tail()
#prey.info()
#

class                                 4
order                                18
family                               63
genus                                92
species                              97
lat                               91909
long                              91965
eventDate                        102140
day                                  31
month                                12
year                                 77
institutionCode                      77
coordinateUncertaintyInMeters      4450
basisOfRecord                         4
individualCount                      42
datasetKey                           88
ID                               111156
bio1                              11778
bio10                             11981
bio11                             11803
bio12                             12117
bio13                             12020
bio14                              4586
bio15                             11848
bio16                             12102
bio17                              9243
bio18                             10698
bio19                             12095
bio2                              11915
bio3                               8723
bio4                              12110
bio5                              11992
bio6                              11934
bio7                              12088
bio8                              11889
bio9                              11980
dist                              11718
dem90_hf                          11904
lc_class                             12
ndvi                              29093
dtype: int64

In [12]:
### Update column names

prey = prey.rename(columns = {'institutionCode' : 'institution_code', 'datasetKey' : 'dataset_key'})
prey

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institution_code,coordinateUncertaintyInMeters,basisOfRecord,individualCount,dataset_key,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,2020,iNaturalist,684.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,1,141.925064,199.384964,89.602631,727.380493,151.920853,1.809903,89.132339,391.141083,7.979710,13.979711,391.141083,139.787125,53.000000,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,2021,iNaturalist,6.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,2,136.366943,165.841537,104.141464,609.651916,126.271736,1.001933,87.368050,318.303192,8.236301,12.390024,318.301269,83.996452,53.266750,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,2021,iNaturalist,31.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,3,82.885788,161.338638,19.747343,724.200195,120.836441,4.910511,70.099121,353.376068,49.060783,77.778824,342.061676,144.624817,47.098640,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,2016,iNaturalist,15.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,4,171.959030,221.238907,130.363754,323.523682,62.686253,1.000000,87.075172,179.273834,4.989321,9.743295,163.154465,118.763413,53.612831,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,2019,iNaturalist,16.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,5,171.996231,214.353073,136.138779,273.203491,58.141060,1.000000,91.661606,162.390411,4.000000,7.109778,142.560562,91.184349,50.718666,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111151,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,33.660853,-115.721380,1980-04-10T00:00:00Z,10.0,4.0,1980,MCZ,3036.0,PRESERVED_SPECIMEN,1.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111152,200.539291,297.044373,111.539291,131.447403,21.313471,0.464611,50.358723,45.637127,7.404018,33.626942,44.287857,158.105041,43.560184,7319.267090,393.674744,34.807846,358.866913,217.827911,227.579758,0.925702,548.778870,barren,1187.127441
111152,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,35.933333,-116.716667,1998-03-26T00:00:00Z,26.0,3.0,1998,MCZ,NaN,PRESERVED_SPECIMEN,2.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111153,230.166946,344.166931,117.216942,49.012608,8.380343,1.000000,50.700531,21.778294,4.391233,9.430344,19.810688,163.872391,39.000000,8878.634766,442.558167,26.608175,415.950012,141.977646,273.793304,7.429875,-13.553053,grassland,792.632141
111153,Insecta,Hymenoptera,Formicidae,Liometopum,Liometopum occidentale,34.156833,-118.726833,2010-05-21T00:00:00Z,21.0,5.0,2010,MCZ,NaN,PRESERVED_SPECIMEN,40.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111154,161.271088,216.747421,116.372208,499.779816,106.116470,0.000000,96.797958,289.033630,4.470360,11.920360,279.654663,128.898209,53.252625,3962.391846,291.092560,51.291302,239.801269,118.917351,209.822205,2.387915,347.122986,grassland,4219.497559
111154,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,32.989167,-116.658500,2010-05-25T00:00:00Z,25.0,5.0,2010,MCZ,NaN,PRESERVED_SPECIMEN,30.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111155,140.342300,217.269943,76.576256,559.577881,102.406273,3.000000,78.449997,293.045471,25.936378,36.503853,270.567810,154.063629,49.683960,5537.141602,315.901031,8.395161,307.505859,83.576256,199.928528,6.917791,981.674377,grassland,4865.626465
111155,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,36.251400,-117.731400,1992-09-02T00:00:00Z,2.0,9.0,1992,NTNU-VM,100000.0,PRESERVED_SPECIMEN,1.0,1bec5de3-758c-4ed2-ab13-1597601ad07a,111156,102.202797,197.274719,18.412592,294.105835,48.132629,6.007638,59.663151,133.747376,27.179491,31.660290,133.747376,141.080276,41.000000,7069.728027,293.179962,-47.896355,341.076324,20.241280,171.378082,23.553705,1913.307861,grassland,1628.940918

In [16]:
# Subsetting, step 1

prey.columns
prey['basisOfRecord'].value_counts()
prey[prey['basisOfRecord'] == 'PRESERVED_SPECIMEN']

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institution_code,coordinateUncertaintyInMeters,basisOfRecord,individualCount,dataset_key,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
1679,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,34.340000,-119.410004,2016-11-29T00:00:00Z,29.0,11.0,2016,NaN,NaN,PRESERVED_SPECIMEN,NaN,d8cd16ba-bb74-4420-821e-083f2bac17c2,1680,154.372528,200.300980,114.870407,475.911072,108.406372,0.000000,100.069076,290.060028,2.000000,6.201149,285.269562,129.936645,57.310860,3349.972412,272.703095,47.010059,225.693039,117.870407,194.108063,0.802846,139.021927,grassland,4859.104980
1680,Insecta,Hymenoptera,Xyelidae,Xyela,Xyela concava,38.759998,-119.660004,2016-06-25T00:00:00Z,25.0,6.0,2016,NaN,NaN,PRESERVED_SPECIMEN,NaN,d8cd16ba-bb74-4420-821e-083f2bac17c2,1681,79.070374,170.401947,-1.718157,452.265961,73.694450,12.075387,58.115467,199.897278,44.346771,44.346771,199.846512,160.934799,44.482346,6806.624023,281.522827,-74.999733,356.522553,6.357229,170.401947,NaN,1877.535400,savanna,3379.441650
1681,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,34.290001,-119.230003,2016-11-24T00:00:00Z,24.0,11.0,2016,NaN,NaN,PRESERVED_SPECIMEN,NaN,d8cd16ba-bb74-4420-821e-083f2bac17c2,1682,155.460648,198.497498,118.571289,430.013184,99.510902,0.000000,99.702957,259.023773,2.000000,5.190607,255.809418,131.268570,59.336895,3137.429199,269.109345,49.446285,219.663071,120.854431,191.976440,2.306774,154.871475,closed_shrubland,3700.706543
1682,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.689999,-117.180000,2016-11-25T00:00:00Z,25.0,11.0,2016,NaN,NaN,PRESERVED_SPECIMEN,NaN,d8cd16ba-bb74-4420-821e-083f2bac17c2,1683,171.975601,212.391007,136.951187,251.560730,54.389912,0.463668,90.511932,151.170273,3.463668,6.463668,132.243484,82.952835,49.488071,2921.583740,251.367142,84.462578,166.904572,139.487518,203.927338,0.592433,NaN,grassland,3317.774902
1683,Insecta,Hymenoptera,Xyelidae,Xyela,Xyela concava,38.660000,-119.589996,2016-06-25T00:00:00Z,25.0,6.0,2016,NaN,NaN,PRESERVED_SPECIMEN,NaN,d8cd16ba-bb74-4420-821e-083f2bac17c2,1684,55.478683,142.975632,-20.735058,588.114624,94.990501,14.623221,58.780247,260.451935,53.345188,53.345188,259.053162,150.054962,43.945538,6525.333984,245.996719,-90.450348,336.447052,-13.016450,142.975632,30.419949,2300.984619,savanna,3184.269775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111151,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,33.660853,-115.721380,1980-04-10T00:00:00Z,10.0,4.0,1980,MCZ,3036.0,PRESERVED_SPECIMEN,1.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111152,200.539291,297.044373,111.539291,131.447403,21.313471,0.464611,50.358723,45.637127,7.404018,33.626942,44.287857,158.105041,43.560184,7319.267090,393.674744,34.807846,358.866913,217.827911,227.579758,0.925702,548.778870,barren,1187.127441
111152,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,35.933333,-116.716667,1998-03-26T00:00:00Z,26.0,3.0,1998,MCZ,NaN,PRESERVED_SPECIMEN,2.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111153,230.166946,344.166931,117.216942,49.012608,8.380343,1.000000,50.700531,21.778294,4.391233,9.430344,19.810688,163.872391,39.000000,8878.634766,442.558167,26.608175,415.950012,141.977646,273.793304,7.429875,-13.553053,grassland,792.632141
111153,Insecta,Hymenoptera,Formicidae,Liometopum,Liometopum occidentale,34.156833,-118.726833,2010-05-21T00:00:00Z,21.0,5.0,2010,MCZ,NaN,PRESERVED_SPECIMEN,40.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111154,161.271088,216.747421,116.372208,499.779816,106.116470,0.000000,96.797958,289.033630,4.470360,11.920360,279.654663,128.898209,53.252625,3962.391846,291.092560,51.291302,239.801269,118.917351,209.822205,2.387915,347.122986,grassland,4219.497559
111154,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,32.989167,-116.658500,2010-05-25T00:00:00Z,25.0,5.0,2010,MCZ,NaN,PRESERVED_SPECIMEN,30.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111155,140.342300,217.269943,76.576256,559.577881,102.406273,3.000000,78.449997,293.045471,25.936378,36.503853,270.567810,154.063629,49.683960,5537.141602,315.901031,8.395161,307.505859,83.576256,199.928528,6.917791,981.674377,grassland,4865.626465
111155,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,36.251400,-117.731400,1992-09-02T00:00:00Z,2.0,9.0,1992,NTNU-VM,100000.0,PRESERVED_SPECIMEN,1.0,1bec5de3-758c-4ed2-ab13-1597601ad07a,111156,102.202797,197.274719,18.412592,294.105835,48.132629,6.007638,59.663151,133.747376,27.179491,31.660290,133.747376,141.080276,41.000000,7069.728027,293.179962,-47.896355,341.076324,20.241280,171.378082,23.553705,1913.307861,grassland,1628.940918

In [19]:
#Subsetting, step 2
#prey[prey['year'].between(1992, 2000)]??

prey.columns
pd.set_option("display.max_rows", None)
prey['year'].value_counts()
prey_years = prey[(prey['year'] >= 1995) & (prey['year'] <= 1999)]
prey_years['year'].value_counts()

year
1996    129
1995    113
1997    112
1999     73
1998     72
Name: count, dtype: int64

In [21]:
#Subsetting, step 3
prey[['species', 'eventDate']]

In [ ]:
#Subsetting, step 4
prey.columns
prey['lat'].value_counts()
prey_box = prey[(prey['lat'] > 37) & (prey['long'] < 39)]
prey_box